# Generated by Django 5.2.8 on 2025-11-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleevent',
            name='analysis_notes',
            field=models.TextField(blank=True, help_text='Detailed research / arbitrage notes for this sale.'),
        ),
    ]
